<?php

namespace src\models\traits;

use ReflectionClass;
use ReflectionProperty;

trait PrimaryKey
{
    protected string $primaryKeyPropertyName = '<property name>';
    protected bool $primaryKeyAutoGenerated = true;

    public static function getPrimaryKeyColumnName(): string
    {
        $reflectionClass = new ReflectionClass(static::class);

        $columns = $reflectionClass
            ->getProperty('columns')
            ->getDefaultValue();

        $primaryKeyPropertyName = $reflectionClass
            ->getProperty('primaryKeyPropertyName')
            ->getDefaultValue();

        return $columns[$primaryKeyPropertyName];
    }

    public function getPrimaryKeyValue(): null|int|float|string
    {
        if (!(new ReflectionProperty($this, $this->primaryKeyPropertyName))->isInitialized($this)) {
            return null;
        }

        return $this->{$this->primaryKeyPropertyName};
    }
}
