<?php

namespace src\models\traits;

use ReflectionProperty;

trait PrimaryKey
{
    protected string $primaryKeyPropertyName = '<property name>';
    protected bool $primaryKeyAutoGenerated = true;

    public function getPrimaryKeyColumnName(): string
    {
        return $this->columns[$this->primaryKeyPropertyName];
    }

    public function getPrimaryKeyValue(): null|int|float|string
    {
        if (!(new ReflectionProperty($this, $this->primaryKeyPropertyName))->isInitialized($this)) {
            return null;
        }

        return $this->{$this->primaryKeyPropertyName};
    }
}
