version: '3.8'

services:
  mysql:
    image: mysql:latest
    command:
      - '--skip-log-bin'
    restart: always
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
    ports:
      - 3306:3306
    volumes:
      - mysql-data:/var/lib/mysql
      # - ./config/mysql:/docker-entrypoint-initdb.d
    networks:
      - public
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      timeout: 2s
      retries: 20

  sentience:
    build: ./docker
    volumes:
      - ./:/app
    command: "php index.php server/start"
    ports:
      - 8000:8000
    networks:
      - public
    depends_on:
      mysql:
        condition: service_healthy

networks:
  public:


volumes:
  mysql-data:
