<?php

namespace src\database\querybuilders;

interface QueryBuilderInterface
{
    public const DATETIME_REGEX = '/^([1-2][0-9]{3})-([0-1][0-9])-([0-3][0-9])(?:( [0-2][0-9]):([0-5][0-9]):([0-5][0-9]))?$/';

    public function select(string $table, array $columns, bool $escapeColumns, array $joins, array $where, array $orderBys, ?int $limit, ?int $offset): array;

    public function insert(string $table, array $values): array;

    public function update(string $table, array $values, array $where): array;

    public function delete(string $table, array $where): array;

    public function create(string $table, bool $ifNotExists, array $properties, string $primaryKey, bool $primaryKeyAutoGenerated): array;

    public function castToDatabase(mixed $value): mixed;

    public function castFromDatabase(string $nativeType, mixed $value): mixed;

    public function getColumnType(string $varType, bool $isPrimaryKey): ?string;
    public function getColumnWithNamespace(string $table, string $column): string;
}
