<?php

namespace src\models;

use DateTime;
use src\database\Database;

class Example extends Model
{
    protected Database $database;
    protected string $table = 'examples';
    protected string $primaryKeyPropertyName = 'id';
    protected bool $primaryKeyAutoGenerated = true;
    protected array $fields = [
        'id' => 'id',
        'name' => 'name',
        'dateCreated' => 'date_created',
    ];

    public int $id;
    public string $name;
    public ?DateTime $dateCreated;
}

?>