<?php

namespace src\models;

use src\database\Database;

class Example extends Model
{
    protected Database $database;
    protected string $table = 'examples';
    protected string $primaryKeyPropertyName = 'id';
    protected bool $primaryKeyAutoGenerated = true;
    protected array $fields = [
        'id' => 'id',
        'firstName' => 'first_name',
        'lastName' => 'last_name'
    ];

    public int $id;
    public ?string $firstName;
    public ?string $lastName;
}

?>