<?php

namespace src\models;

use DateTime;
use src\database\Database;
use src\models\relations\HasOne;

class Example extends Model
{
    protected Database $database;
    protected string $table = 'examples';
    protected string $primaryKeyPropertyName = 'id';
    protected bool $primaryKeyAutoGenerated = true;
    protected array $fields = [
        'id' => 'id',
        'name' => 'name',
        'dateCreated' => 'date_created',
    ];

    protected array $onSave = [
        'name' => 'formatName'
    ];

    public int $id;
    public ?string $name;
    public ?DateTime $dateCreated;

    protected function formatName(?string $name): ?string
    {
        if (!$name) {
            return null;
        }

        return ucfirst($name);
    }

    protected function registerRelations(): void
    {
        $this->registerRelation(
            new HasOne(
                Example::class,
                'example_id'
            )
        );
    }
}
