<?php

namespace src\models;

use DateTime;
use src\database\Database;

class Migration extends Model
{
    protected string $table = 'migrations';
    protected string $primaryKeyPropertyName = 'id';
    protected bool $primaryKeyAutoGenerated = true;
    protected array $columns = [
        'id' => 'id',
        'filename' => 'filename',
        'appliedAt' => 'applied_at'
    ];

    public int $id;
    public string $filename;
    public ?DateTime $appliedAt;
}
