<?php

namespace src\models;

use src\database\Database;

class Model
{
    protected Database $database;
    protected string $table = '';
    protected string $primaryKeyPropertyName = 'id';
    protected bool $primaryKeyAutoGenerated = true;
    protected array $fields = [
        'id' => 'id'
    ];

    public function __construct(Database $database)
    {
        $this->database = $database;
    }

    public function hydrate(): static
    {
        $data = $this->database->query()
            ->table($this->table)
            ->columns(array_values($this->fields))
            ->selectAssocSingle();

        foreach ($data as $key => $value) {
            $this->{$key} = $value;
        }

        return $this;
    }

    public function insert(): static
    {
        $insertableValues = $this->getNonPrimaryKeyFields();

        $query = $this->database->query()
            ->table($this->table)
            ->values($insertableValues);

        if ($this->primaryKeyAutoGenerated) {
            $primaryKeyColumnName = $this->getPrimaryKeyColumnName();
            $insertedId = $query->insertWithLastId($primaryKeyColumnName);

            $this->{$primaryKeyColumnName} = $insertedId;
        } else {
            $query->insert();
        }

        return $this;
    }

    public function update(): static
    {
        $updatableValues = $this->getNonPrimaryKeyFields();

        $primaryKeyColumnName = $this->getPrimaryKeyColumnName();

        $this->database->query()
            ->table($this->table)
            ->values($updatableValues)
            ->where(
                $primaryKeyColumnName,
                '=',
                $this->getPrimaryKeyValue()
            )
            ->update();

        return $this;
    }

    public function getPrimaryKeyColumnName(): int|string
    {
        return $this->fields[$this->primaryKeyPropertyName];
    }

    public function getPrimaryKeyValue(): int|string
    {
        return $this->{$this->primaryKeyPropertyName};
    }

    protected function getNonPrimaryKeyFields(): array
    {
        $nonPkValues = [];

        foreach ($this->fields as $propertyName => $columnName) {
            if ($propertyName == $this->primaryKeyPropertyName) {
                continue;
            }

            $key = $columnName;
            $value = $this->{$propertyName};

            $nonPkValues[$key] = $value;
        }

        return $nonPkValues;
    }
}

?>